/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointpolygon;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Polygon;

/**
 *
 * @author jethro
 */
public class DrawPanel extends javax.swing.JPanel {

    public Polygon poly;
    public Point point;
    boolean inside;
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        poly = new Polygon(new int[]{10,110,150,110,50},new int[]{10,10,100,200,200},5);
        point = new Point(-10,-10);
        inside = false;
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D gfx = (Graphics2D)g;
        
        gfx.setColor(Color.yellow);
        if (this.inside){
            gfx.fillPolygon(poly);
        }
        
        gfx.setColor(Color.BLACK);
            gfx.drawPolygon(poly);
        
        gfx.drawLine(point.x-5, point.y-5, point.x+5, point.y+5);
        gfx.drawLine(point.x-5, point.y+5, point.x+5, point.y-5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        point.setLocation(evt.getX(),evt.getY());
        Algorithms.PositionEnum res = Algorithms.pointPolygonWinding(point,poly);
        if (res == Algorithms.PositionEnum.INSIDE){
            inside = true;
            System.out.println("Inside");
        } else if (res == Algorithms.PositionEnum.OUTSIDE){
            inside = false;
            System.out.println("Outside");
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
